SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1 AFTER description;

ALTER TABLE inventory_movements
    ADD COLUMN IF NOT EXISTS previous_stock DECIMAL(14, 3) NULL AFTER quantity,
    ADD COLUMN IF NOT EXISTS new_stock DECIMAL(14, 3) NULL AFTER previous_stock,
    ADD COLUMN IF NOT EXISTS status ENUM('COMPLETED', 'REVERSED', 'PENDING') NOT NULL DEFAULT 'COMPLETED' AFTER moved_at;

SET FOREIGN_KEY_CHECKS = 1;
